name: PcCoin
version: $1.0
main: com.xariyx.Main
api-version: 1.16
authors: [ Xariyx ]
description: Currency plugin
commands:
  pccoin:
    aliases: [pcc, pc, coin]
    description: "PcCoin plugin commands"
    usage: /pccoin <buff/message/teleport>
