name: PcCoin
version: ${project.version}
main: com.xariyx.Main
api-version: 1.16
authors: [ Xariyx ]
description: Currency plugin
commands:
  pccoin:
    aliases: [pcc, pc, coin]
    description: "PcCoin admin tools"
    usage: /pccoin <set/get/addmob/addblock>
